name: "🪲 Bug Report"
description: "Report unexpected behavior, crashes, or incorrect output."
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - jrivas12

body:
  - type: markdown
    attributes:
      value: |
        ## 🪲 Bug Report
        Thank you for helping improve **Alchemist**.  
        Please complete the sections below to help us reproduce and resolve the issue efficiently.

  - type: textarea
    id: summary
    attributes:
      label: "🧩 Summary"
      description: "Briefly describe what went wrong and where."
      placeholder: "Ex: Program crashes when selecting QuickSort from the main menu."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "🔁 Steps to Reproduce"
      description: "Please list the steps needed to reproduce the bug."
      placeholder: |
        1. Run `menu_Orchestrator.cpp`
        2. Choose option 3 (Sorting Algorithms)
        3. Select 'MergeSort'
        4. Observe incorrect sorting order in output table
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "✅ Expected Behavior"
      description: "What did you expect to happen?"
      placeholder: "Ex: Array should be sorted in ascending order with correct indices."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "❌ Actual Behavior"
      description: "What actually happened?"
      placeholder: "Ex: Array prints partially unsorted or with duplicate values."
    validations:
      required: true

  - type: dropdown
    id: compiler
    attributes:
      label: "🧱 Compiler Version"
      description: "Which compiler and standard are you using?"
      options:
        - "g++ (C++17)"
        - "g++ (C++20)"
        - "clang++ (C++17)"
        - "MSVC (Visual Studio 2022)"
        - "Other / Unknown"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: "💻 Operating System"
      description: "What OS environment are you running this in?"
      options:
        - "Windows 10 / 11"
        - "Ubuntu / Linux"
        - "macOS"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "🧾 Terminal Output / Error Logs"
      description: "Please paste any compiler or runtime output that shows the issue."
      render: shell
      placeholder: "./alchemist: line 42: segmentation fault (core dumped)"
    validations:
      required: false

  - type: textarea
    id: files
    attributes:
      label: "📂 Affected Files"
      description: "Which files or modules are likely involved?"
      placeholder: "Ex: menu_Orchestrator.cpp, ArrayStats.h"
    validations:
      required: false

  - type: checkboxes
    id: confirmation
    attributes:
      label: "✅ Confirmation"
      description: "Before submitting, please confirm the following:"
      options:
        - label: "I’ve searched open issues to ensure this bug hasn’t been reported."
          required: true
        - label: "I’ve included enough details and steps to reproduce this issue."
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        🧠 _Tip: Include screenshots or terminal snippets if they help illustrate the problem._  
        _Thanks for taking the time to make **Alchemist** more reliable and teachable._
