blank_issues_enabled: false
contact_links:
  - name: 💬 Community Discussions
    url: https://github.com/jrivas12/alchemist/discussions
    about: Ask questions, share ideas, or get help from other contributors.
